FROM python:3.12.1-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    libgl1  \
    libglx-mesa0 \
    libglib2.0-0 \
    && rm -rf /var/lib/apt/lists/*


COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY api_manager.py .
COPY DbLibrary.py .
COPY libs/ ./libs/
COPY pretrained/ ./pretrained/
COPY init_db.sql .

CMD ["python", "api_manager.py"]